name: Build PDFs

on:
  push:

jobs:
  build-pdf:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout
     uses: actions/checkout@v5

   - name: Run pdflatex
     uses: xu-cheng/texlive-action@v3
     with:
       scheme: full
       run: |
         cd rules
         pdflatex battletech-outworlds-wastes.tex
         pdflatex battletech-outworlds-wastes.tex
         pdflatex battletech-outworlds-wastes.tex
         pdflatex battletech-outworlds-wastes-quickstart.tex
         pdflatex battletech-outworlds-wastes-quickstart.tex
         pdflatex battletech-outworlds-wastes-event.tex
         pdflatex battletech-outworlds-wastes-event.tex
         pdflatex battletech-outworlds-wastes-errata.tex
         pdflatex battletech-outworlds-wastes-errata.tex
         pdflatex battletech-outworlds-wastes-instant-action.tex
         pdflatex battletech-outworlds-wastes-instant-action.tex
         cd ..
         mv rules/*.pdf .
         mv scenarios/*/*.pdf .
         ls | grep -vE ".pdf|.md" | xargs rm -rf

   - name: Publish PDF
     uses: peaceiris/actions-gh-pages@v4
     with:
       github_token: ${{ secrets.GITHUB_TOKEN }}
       publish_dir: .
       publish_branch: ${{ github.ref == 'refs/heads/main' && 'rules-pdf' || 'rules-pdf-staging' }}
       force_orphan: true
